Update tutorial 13 & 14 with libbpf-bootstrap
eunomia-bpf/bpf-developer-tutorial pull request #7
Opened 2023-01-21 13:16 UTC by Officeyutong

# Tutorial 13 & 14 with libbpf-bootstrap

## Description

https://github.com/eunomia-bpf/bpf-developer-tutorial/issues/3

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-01-21 15:59 UTC, yunwei37 requested changes
以及一些 linter 的问题可以修复一下? 你可以在 vscode 里面安装一下 markdown linter

2023-01-21 15:59 UTC, yunwei37 commented on 13-tcpconnlat/README.md
> +对于使用 `libbpf-bootstrap` 的开发，具体见 [tcpconnlat-libbpf-bootstrap.md](tcpconnlat-libbpf-bootstrap.md)
可以把这些部分全部放在 README.md 里面吗，不需要分成两个文档会不会更好一点?

2023-01-21 16:41 UTC, Officeyutong commented on 13-tcpconnlat/README.md
> +对于使用 `libbpf-bootstrap` 的开发，具体见 [tcpconnlat-libbpf-bootstrap.md](tcpconnlat-libbpf-bootstrap.md)
markdown liniter 给所有的md文档全报了一堆问题，全都处理下么

2023-01-22 08:08 UTC, yunwei37 commented on 13-tcpconnlat/README.md
> +对于使用 `libbpf-bootstrap` 的开发，具体见 [tcpconnlat-libbpf-bootstrap.md](tcpconnlat-libbpf-bootstrap.md)
不必了吧，剩下可以之后开个另外一个 pr 解决

2023-01-22 08:08 UTC, yunwei37 approved these changes

2023-01-22 08:08 UTC, merged